center_sph_matrices.o: $(MHD_FDM_DIR)/center_sph_matrices.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
select_sph_r_mat_magne_BC.o: $(MHD_FDM_DIR)/select_sph_r_mat_magne_BC.f90 m_precision.o m_constants.o m_machine_parameter.o m_ludcmp_3band.o t_physical_property.o t_spheric_rj_data.o t_sph_matrices.o t_boundary_params_sph_MHD.o t_coef_fdm2_centre.o set_radial_mat_sph.o set_sph_scalar_matrix_ICB.o center_sph_matrices.o set_sph_scalar_matrix_CMB.o
	$(F90) -c $(F90OPTFLAGS) $<
select_sph_r_mat_vort_BC.o: $(MHD_FDM_DIR)/select_sph_r_mat_vort_BC.f90 m_precision.o calypso_mpi.o m_constants.o m_machine_parameter.o m_ludcmp_3band.o t_physical_property.o t_spheric_rj_data.o t_sph_matrices.o t_boundary_params_sph_MHD.o t_coef_sph_velocity_BCs.o t_coef_fdm2_centre.o set_radial_mat_sph.o set_sph_scalar_matrix_ICB.o center_sph_matrices.o set_sph_scalar_matrix_CMB.o
	$(F90) -c $(F90OPTFLAGS) $<
set_sph_scalar_matrix_CMB.o: $(MHD_FDM_DIR)/set_sph_scalar_matrix_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
set_sph_scalar_matrix_ICB.o: $(MHD_FDM_DIR)/set_sph_scalar_matrix_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fix_scalar_CMB.o: $(MHD_FDM_DIR)/sph_exp_fix_scalar_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fix_scalar_ICB.o: $(MHD_FDM_DIR)/sph_exp_fix_scalar_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fix_vector_CMB.o: $(MHD_FDM_DIR)/sph_exp_fix_vector_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fix_vector_ICB.o: $(MHD_FDM_DIR)/sph_exp_fix_vector_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fixed_flux_CMB.o: $(MHD_FDM_DIR)/sph_exp_fixed_flux_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_fixed_flux_ICB.o: $(MHD_FDM_DIR)/sph_exp_fixed_flux_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_free_slip_CMB.o: $(MHD_FDM_DIR)/sph_exp_free_slip_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_free_slip_ICB.o: $(MHD_FDM_DIR)/sph_exp_free_slip_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_no_condition_CMB.o: $(MHD_FDM_DIR)/sph_exp_no_condition_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_no_condition_ICB.o: $(MHD_FDM_DIR)/sph_exp_no_condition_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_nod_insulate_CMB.o: $(MHD_FDM_DIR)/sph_exp_nod_insulate_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_nod_insulate_ICB.o: $(MHD_FDM_DIR)/sph_exp_nod_insulate_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_nod_psd_vacuum_CMB.o: $(MHD_FDM_DIR)/sph_exp_nod_psd_vacuum_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_nod_psd_vacuum_ICB.o: $(MHD_FDM_DIR)/sph_exp_nod_psd_vacuum_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_rigid_CMB.o: $(MHD_FDM_DIR)/sph_exp_rigid_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
sph_exp_rigid_ICB.o: $(MHD_FDM_DIR)/sph_exp_rigid_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm1_free_rotate_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm1_free_rotate_CMB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm1_free_rotate_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm1_free_rotate_ICB.f90 m_precision.o m_constants.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm2_centre.o: $(MHD_FDM_DIR)/t_coef_fdm2_centre.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm2_free_slip_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm2_free_slip_CMB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm2_free_slip_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm2_free_slip_ICB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm2_scalar_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm2_scalar_CMB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm2_scalar_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm2_scalar_ICB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm3_n2e_free_vp_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm3_n2e_free_vp_CMB.f90 m_precision.o m_constants.o t_coef_fdm3_n2e_zero_vp_CMB.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm3_n2e_free_vp_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm3_n2e_free_vp_ICB.f90 m_precision.o m_constants.o t_coef_fdm3_n2e_zero_vp_ICB.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm3_n2e_zero_vp_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm3_n2e_zero_vp_CMB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm3_n2e_zero_vp_CTR.o: $(MHD_FDM_DIR)/t_coef_fdm3_n2e_zero_vp_CTR.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm3_n2e_zero_vp_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm3_n2e_zero_vp_ICB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm4_free_vpol_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm4_free_vpol_CMB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm4_free_vpol_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm4_free_vpol_ICB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm4_vpol_centre.o: $(MHD_FDM_DIR)/t_coef_fdm4_vpol_centre.f90 m_precision.o m_constants.o t_fdm_coefs.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm4_zero_vpol_CMB.o: $(MHD_FDM_DIR)/t_coef_fdm4_zero_vpol_CMB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_fdm4_zero_vpol_ICB.o: $(MHD_FDM_DIR)/t_coef_fdm4_zero_vpol_ICB.f90 m_precision.o m_constants.o cal_inverse_small_matrix.o
	$(F90) -c $(F90OPTFLAGS) $<
t_coef_sph_velocity_BCs.o: $(MHD_FDM_DIR)/t_coef_sph_velocity_BCs.f90 m_precision.o m_machine_parameter.o t_spheric_rj_data.o t_coef_fdm2_free_slip_ICB.o t_coef_fdm2_free_slip_CMB.o t_coef_fdm3_n2e_zero_vp_ICB.o t_coef_fdm3_n2e_zero_vp_CMB.o t_coef_fdm3_n2e_zero_vp_CTR.o t_coef_fdm3_n2e_free_vp_ICB.o t_coef_fdm3_n2e_free_vp_CMB.o t_coef_fdm4_zero_vpol_ICB.o t_coef_fdm4_zero_vpol_CMB.o t_coef_fdm4_free_vpol_ICB.o t_coef_fdm4_free_vpol_CMB.o t_coef_fdm4_vpol_centre.o t_coef_fdm1_free_rotate_ICB.o t_coef_fdm1_free_rotate_CMB.o t_fdm_coefs.o t_boundary_params_sph_MHD.o
	$(F90) -c $(F90OPTFLAGS) $<

