analyzer_fujitsu_test.o: $(SPH_FUJITSU_TEST)/analyzer_fujitsu_test.f90 m_precision.o calypso_mpi.o m_machine_parameter.o m_work_time.o m_elapsed_labels_4_MHD.o m_elapsed_labels_SEND_RECV.o m_SPH_MHD_model_data.o m_MHD_step_parameter.o t_SPH_mesh_field_data.o t_ctl_data_MHD.o t_viz_sections.o t_SPH_MHD_zonal_mean_viz.o t_sph_trans_arrays_MHD.o t_comm_table.o FEM_analyzer_sph_MHD.o SPH_analyzer_MHD.o init_sph_MHD_elapsed_label.o t_ctl_data_sph_MHD_psf.o input_control_sph_MHD.o FEM_to_PSF_bridge.o
	$(F90) -c $(F90OPTFLAGS) $<
main_fujitsu_test.o: $(SPH_FUJITSU_TEST)/main_fujitsu_test.f90 m_precision.o calypso_mpi.o analyzer_fujitsu_test.o
	$(F90) -c $(F90OPTFLAGS) $<

