analyzer_assemble_sph.o: $(MERGE_SRCDIR)/analyzer_assemble_sph.f90 m_precision.o m_constants.o calypso_mpi.o m_machine_parameter.o r_interpolate_marged_sph.o t_SPH_mesh_field_data.o t_time_data.o t_field_data_IO.o t_control_data_4_merge.o t_control_param_assemble.o t_spectr_data_4_assemble.o t_check_and_make_SPH_mesh.o new_SPH_restart.o parallel_assemble_sph.o copy_rj_phys_data_4_IO.o assemble_sph_fields.o set_control_newsph.o field_IO_select.o m_error_IDs.o bcast_4_assemble_sph_ctl.o sph_file_MPI_IO_select.o sph_file_IO_select.o share_spectr_index_data.o count_nnod_4_asseble_sph.o parallel_gen_sph_grids.o set_field_file_names.o share_field_data.o
	$(F90) -c $(F90OPTFLAGS) $<
main_assemble_sph.o: $(MERGE_SRCDIR)/main_assemble_sph.f90 m_precision.o calypso_mpi.o analyzer_assemble_sph.o
	$(F90) -c $(F90OPTFLAGS) $<

