SPH_analyzer_snap_w_vizs.o: $(SPH_SNAP_MAINDIR)/SPH_analyzer_snap_w_vizs.f90 m_precision.o m_work_time.o m_elapsed_labels_4_MHD.o t_SPH_MHD_model_data.o t_control_parameter.o t_phys_address.o t_MHD_file_parameter.o t_SPH_mesh_field_data.o t_FEM_mesh_field_data.o t_boundary_data_sph_MHD.o t_work_SPH_MHD.o t_sph_mhd_monitor_data_IO.o t_mesh_SR.o m_constants.o calypso_mpi.o m_machine_parameter.o t_sph_boundary_input_data.o set_control_sph_mhd.o adjust_reference_fields.o set_bc_sph_mhd.o material_property.o init_sphrical_transform_MHD.o init_radial_infos_sph_mhd.o const_radial_mat_4_sph.o r_interpolate_sph_data.o sph_mhd_rst_IO_control.o check_dependency_for_MHD.o input_control_sph_MHD.o cal_write_sph_monitor_data.o cal_nonlinear.o cal_sol_sph_MHD_crank.o lead_fields_4_sph_mhd.o output_viz_file_control.o sph_radial_grad_4_magne.o
	$(F90) -c $(F90OPTFLAGS) $<
analyzer_sph_snap_w_psf.o: $(SPH_SNAP_MAINDIR)/analyzer_sph_snap_w_psf.f90 m_precision.o calypso_mpi.o m_work_time.o m_elapsed_labels_4_MHD.o m_elapsed_labels_SEND_RECV.o m_machine_parameter.o t_spherical_MHD.o t_sph_MHD_w_psf.o t_ctl_data_MHD.o t_ctl_data_sph_MHD_w_psf.o t_viz_sections.o t_SPH_MHD_zmean_sections.o init_sph_MHD_elapsed_label.o input_control_sph_MHD.o SPH_analyzer_snap_w_vizs.o FEM_analyzer_sph_MHD.o FEM_to_PSF_bridge.o output_viz_file_control.o set_time_step_params.o
	$(F90) -c $(F90OPTFLAGS) $<
main_control_MHD_psf_check.o: $(SPH_SNAP_MAINDIR)/main_control_MHD_psf_check.f90 m_precision.o t_ctl_data_MHD.o t_ctl_data_sph_MHD_w_psf.o t_read_control_elements.o write_control_elements.o
	$(F90) -c $(F90OPTFLAGS) $<
main_sph_snapshot_w_psf.o: $(SPH_SNAP_MAINDIR)/main_sph_snapshot_w_psf.f90 m_precision.o calypso_mpi.o analyzer_sph_snap_w_psf.o
	$(F90) -c $(F90OPTFLAGS) $<

